// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIBrxK-YYwcuj1z7Dqws_WaIAWLN0N5hk',
    appId: '1:1062338464467:web:2bbbcbaca10ef1304fa226',
    messagingSenderId: '1062338464467',
    projectId: 'event-web-39c84',
    authDomain: 'event-web-39c84.firebaseapp.com',
    storageBucket: 'event-web-39c84.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbysmdCJRlrmFfMvwDfYQAPCvzvEB7TjQ',
    appId: '1:1062338464467:android:31b2b5f039485d814fa226',
    messagingSenderId: '1062338464467',
    projectId: 'event-web-39c84',
    storageBucket: 'event-web-39c84.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfKwZFAb2Z06i_h37iM8mmO0UyyK0er-s',
    appId: '1:1062338464467:ios:bcf2f4d723c9dac94fa226',
    messagingSenderId: '1062338464467',
    projectId: 'event-web-39c84',
    storageBucket: 'event-web-39c84.firebasestorage.app',
    iosBundleId: 'com.example.eventManagementWeb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfKwZFAb2Z06i_h37iM8mmO0UyyK0er-s',
    appId: '1:1062338464467:ios:bcf2f4d723c9dac94fa226',
    messagingSenderId: '1062338464467',
    projectId: 'event-web-39c84',
    storageBucket: 'event-web-39c84.firebasestorage.app',
    iosBundleId: 'com.example.eventManagementWeb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIBrxK-YYwcuj1z7Dqws_WaIAWLN0N5hk',
    appId: '1:1062338464467:web:d384f95b33cf51d54fa226',
    messagingSenderId: '1062338464467',
    projectId: 'event-web-39c84',
    authDomain: 'event-web-39c84.firebaseapp.com',
    storageBucket: 'event-web-39c84.firebasestorage.app',
  );
}
